% Author: Woojae Jeong

%% Bad channel interpolation

if ~isempty(char(chan{:}))
    % Process: Set bad channels

    sFiles = bst_process('CallProcess', 'process_channel_setbad', sFiles, [], ...
        'sensortypes', chan); % Specify bad channel names

    % Process: Interpolate bad electrodes
    sFiles = bst_process('CallProcess', 'process_eeg_interpbad', sFiles, [], ...
        'maxdist',     5, ...
        'sensortypes', 'EEG');
end

%% Import bad time segment
RawFiles = {[sDirectory,'/events_',SubjectNames{1},'_badseg.mat']};

% Process: Import from file
sFiles = bst_process('CallProcess', 'process_evt_import', sFiles, [], ...
    'evtfile', {RawFiles{1}, 'BST'}, ...
    'evtname', 'new', ...
    'delete',  0);

%% ICA
sFiles = bst_process('CallProcess', 'process_ica', sFiles, [], ...
    'timewindow',   [], ...
    'eventname',    '', ...
    'eventtime',    [-0.2, 0.2], ...
    'sensortypes',  'EEG', ...
    'ignorebad',    1, ...
    'bandpass',     [0, 0], ...
    'resample',     0, ...
    'usessp',       1, ...
    'method',       'picard', ...  % Picard:    Ablin, Cardoso & Gramfort (IEEE TSP 2018) 
    'nicacomp',     0, ...
    'icasort',      'Fp1, Fp2', ...
    'saveerp',      0);

save([sDirectory,'/',SubjectNames{1},'_preprocessed_sFiles_ICA.mat'],'sFiles','SubjectNames','protocolName','name','-v7.3');
